//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lucas.Solutions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lucas.Solutions.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear.
        /// </summary>
        internal static string CMD_CLEAR_EXAMPLE {
            get {
                return ResourceManager.GetString("CMD_CLEAR_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the screen.
        /// </summary>
        internal static string CMD_CLEAR_SUMMARY {
            get {
                return ResourceManager.GetString("CMD_CLEAR_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear.
        /// </summary>
        internal static string CMD_CLEAR_SYNTAX {
            get {
                return ResourceManager.GetString("CMD_CLEAR_SYNTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the number of existing shape elements. If one or more shape types are specifies as arguments the result will be filtered. If no argument is specified all it will be the total of all..
        /// </summary>
        internal static string CMD_COUNT_SUMMARY {
            get {
                return ResourceManager.GetString("CMD_COUNT_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to count [shape1, ... shapeN].
        /// </summary>
        internal static string CMD_COUNT_SYNTAX {
            get {
                return ResourceManager.GetString("CMD_COUNT_SYNTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exit.
        /// </summary>
        internal static string CMD_EXIT_EXAMPLE {
            get {
                return ResourceManager.GetString("CMD_EXIT_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit and close the application.
        /// </summary>
        internal static string CMD_EXIT_SUMMARY {
            get {
                return ResourceManager.GetString("CMD_EXIT_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exit.
        /// </summary>
        internal static string CMD_EXIT_SYNTAXIS {
            get {
                return ResourceManager.GetString("CMD_EXIT_SYNTAXIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help run.
        /// </summary>
        internal static string CMD_HELP_EXAMPLE {
            get {
                return ResourceManager.GetString("CMD_HELP_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists one or more  and command definitions. If no argument is specifies it will list all command definitions..
        /// </summary>
        internal static string CMD_HELP_SUMMARY {
            get {
                return ResourceManager.GetString("CMD_HELP_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help [cmd1, ... cmdN].
        /// </summary>
        internal static string CMD_HELP_SYNTAX {
            get {
                return ResourceManager.GetString("CMD_HELP_SYNTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to master transfers.
        /// </summary>
        internal static string CMD_MASTER_EXAMPLE {
            get {
                return ResourceManager.GetString("CMD_MASTER_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display masterdata. If one or more set are specifies as arguments the result will be filtered. If no argument is specified all masterdata will be printed..
        /// </summary>
        internal static string CMD_MASTER_SUMMARY {
            get {
                return ResourceManager.GetString("CMD_MASTER_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to master [set1, ... setN].
        /// </summary>
        internal static string CMD_MASTER_SYNTAX {
            get {
                return ResourceManager.GetString("CMD_MASTER_SYNTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to run UploadOrders, DownloadStatus.
        /// </summary>
        internal static string CMD_RUN_EXAMPLE {
            get {
                return ResourceManager.GetString("CMD_RUN_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts a transfer o more. If no transfer name is specified, all transders are run in parallel..
        /// </summary>
        internal static string CMD_RUN_SUMMARY {
            get {
                return ResourceManager.GetString("CMD_RUN_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to run [transfer1, ...transferN].
        /// </summary>
        internal static string CMD_RUN_SYNTAX {
            get {
                return ResourceManager.GetString("CMD_RUN_SYNTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scheduler start.
        /// </summary>
        internal static string CMD_SCHEDULER_EXAMPLE {
            get {
                return ResourceManager.GetString("CMD_SCHEDULER_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start or stop the scheduler. For scheduler status use with no parameter..
        /// </summary>
        internal static string CMD_SCHEDULER_SUMMARY {
            get {
                return ResourceManager.GetString("CMD_SCHEDULER_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scheduler [start | stop].
        /// </summary>
        internal static string CMD_SCHEDULER_SYNTAX {
            get {
                return ResourceManager.GetString("CMD_SCHEDULER_SYNTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status UploadOrders, DownloadStatus.
        /// </summary>
        internal static string CMD_STATUS_EXAMPLE {
            get {
                return ResourceManager.GetString("CMD_STATUS_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the status of one or more transfers. If no transfer name is specified, all transfers statuses are displayed..
        /// </summary>
        internal static string CMD_STATUS_SUMMARY {
            get {
                return ResourceManager.GetString("CMD_STATUS_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status [transfer1, ... transferN].
        /// </summary>
        internal static string CMD_STATUS_SYNTAX {
            get {
                return ResourceManager.GetString("CMD_STATUS_SYNTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer \&quot;{0}\&quot; completed successfuly..
        /// </summary>
        internal static string CMD_TRANSFER_SUCCESS {
            get {
                return ResourceManager.GetString("CMD_TRANSFER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires {1} argument values and we got {2}..
        /// </summary>
        internal static string ERROR_ARGUMENT_COUNT {
            get {
                return ResourceManager.GetString("ERROR_ARGUMENT_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse to {0} token \&quot;{1}\&quot; at position {2}..
        /// </summary>
        internal static string ERROR_ARGUMENT_TYPE {
            get {
                return ResourceManager.GetString("ERROR_ARGUMENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t write messages to queue \&quot;{0}\&quot;..
        /// </summary>
        internal static string ERROR_CANT_WRITE_TO_QUEUE {
            get {
                return ResourceManager.GetString("ERROR_CANT_WRITE_TO_QUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; was not found..
        /// </summary>
        internal static string ERROR_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =&gt; Error: .
        /// </summary>
        internal static string ERROR_PRINT {
            get {
                return ResourceManager.GetString("ERROR_PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request doesn&apos;t seem valid..
        /// </summary>
        internal static string ERROR_UNKNOW_REQUEST {
            get {
                return ResourceManager.GetString("ERROR_UNKNOW_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =&gt; {0}:\n\tSyntax: {1}:\n\tSummary: {2}\n\tExample: {3}.
        /// </summary>
        internal static string HELP_CMD_DEFINITION_FORMAT {
            get {
                return ResourceManager.GetString("HELP_CMD_DEFINITION_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =&gt; {0}:\n\tSummary: {1}\n\tExample: {2}.
        /// </summary>
        internal static string HELP_SHAPE_DEFINITION_FORMAT {
            get {
                return ResourceManager.GetString("HELP_SHAPE_DEFINITION_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =&gt; Listing Shapes containin point at {0} {1}....
        /// </summary>
        internal static string LISTING_SHAPES_CONTAINING_POINT {
            get {
                return ResourceManager.GetString("LISTING_SHAPES_CONTAINING_POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =&gt; Listing Shapes overlaping {0} {1}....
        /// </summary>
        internal static string LISTING_SHAPES_OVERLAPING_SHAPE {
            get {
                return ResourceManager.GetString("LISTING_SHAPES_OVERLAPING_SHAPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; .
        /// </summary>
        internal static string PROMPT {
            get {
                return ResourceManager.GetString("PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; already exists. Do you want to overwrite it (y/n)?.
        /// </summary>
        internal static string PROMPT_FILE_OVERWRITE {
            get {
                return ResourceManager.GetString("PROMPT_FILE_OVERWRITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =&gt; Count: {0}.
        /// </summary>
        internal static string SHAPE_COUNT_FORMAT {
            get {
                return ResourceManager.GetString("SHAPE_COUNT_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A poligon. The number of sides is 3 or more..
        /// </summary>
        internal static string SHAPE_POLYGON_SUMMARY {
            get {
                return ResourceManager.GetString("SHAPE_POLYGON_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =&gt; shape {0}: .
        /// </summary>
        internal static string SHAPE_PRINT {
            get {
                return ResourceManager.GetString("SHAPE_PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: .
        /// </summary>
        internal static string WARNING_PRINT {
            get {
                return ResourceManager.GetString("WARNING_PRINT", resourceCulture);
            }
        }
    }
}
